apiVersion: v2
name: rocketmq-cluster
description: RocketMQ Helm chart
type: application

version: 12.4.3
appVersion: '5.3.3'

maintainers:
  - name: midy177
    url: 'https://github.com/midy177/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache