apiVersion: v2
name: rocketmq-cluster
description: RocketMQ Helm chart
type: application

version: 12.4.1
appVersion: '5.3.2'

maintainers:
  - name: itboon
    url: 'https://github.com/itboon/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache