apiVersion: v2
name: rocketmq
description: RocketMQ Helm chart
type: application

version: 12.5.1
appVersion: '5.3.3'

maintainers:
  - name: itboon
    url: 'https://github.com/itboon/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache